Add Scala SMT-LIB dependency
cuplv/cuanto pull request #51
Opened 2017-06-21 17:19 UTC by octalsrc

This PR adds EPFL-LARA's [`scala-smtlib`-`v0.2.1`](https://github.com/regb/scala-smtlib) to our project's dependencies and provides a [ScalaTest suite](https://github.com/cuplv/cuanto/blob/4fcedbdaa686209d6d61ecac48d7652e07c20e30/src/test/scala/edu/colorado/plv/cuanto/example/ScalaSmtlibExample.scala) that verifies it works and demonstrates how to construct SMT scripts and call the solver.

2017-06-21 20:19 UTC, octalsrc commented
I think we should begin pruning the code patterns `codacy` enforces, starting with "Enforce sorting imports alphabetically".

1. I'm not sure how that one even applies where it's been [marked here](https://www.codacy.com/app/cuplv/cuanto/pullRequest?prid=725083)
2. In general it's useful to group imports by function or category before alphabetically

I want my green check-mark!

2017-06-23 16:04 UTC, smover requested changes
The PR is good: the only thing I would like to double check with you is how we handle the dependency with z3 itself.

Could you look at the comment?

2017-06-23 16:04 UTC, smover commented on src/test/scala/edu/colorado/plv/cuanto/example/ScalaSmtlibExample.scala
> +import smtlib.interpreters.{
Try to fix the codacity issue for this import (and maybe for the one above).
If we do not figure out what is causing it we can disable the check.

2017-06-23 16:04 UTC, smover commented on project/Dependencies.scala
> +  lazy val scalaSMTLIB = "com.regblanc" %% "scala-smtlib" % "0.2.1"
Dependency questions:
  - Are we requiring z3 as an external dependency for the whole project?
  - Is z3 installed automatically by scala-smtlib or the user must install it manually?
  - What does it happen if one does not have z3 installed on his machine?

We should understand the better way of adding it as dependency.

2017-06-23 16:16 UTC, octalsrc commented
We will want to figure out for the future how to exclude things that depend on z3 (and other future non-sbt-resolvable dependencies) in the default sbt actions, and have some flag for bringing them in.

As a small note, I've added the "Slow" flag on the SMT example tests, so they can be excluded easily along with the soot-loading things.

2017-06-23 16:34 UTC, smover approved these changes

2017-06-23 16:35 UTC, merged